name: Test React Application

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
    
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies and Build
      run: ./scripts/install-dependencies-and-build.sh
    - name: Run Unit and Integration Tests
      run: ./scripts/test.sh
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          cypress/screenshots
          cypress/videos
